name: shell command

on: [push]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: print string
        run: echo "First manual workflow run"
      - name: check node version
        run: |
          node --version
          npm --version